trigger:
  branches:
    include:
      - main

variables: 
  - name: serviceConnectionName
    value: YOUR SERVICE CONNECTION HERE
  - name: terraformBackendStorageAccountName
    value: YOUR TERRAFORM BACKEND STORAGE ACCOUNT NAME HERE
  - name: terraformBackendStorageContainerName
    value: YOUR TERRAFORM BACKEND STORAGE CONTAINER NAME HERE
  - name: terraformBackendResourceGroupName
    value: YOUR TERRAFORM BACKEND RESOURCE GROUP NAME HERE
  - name: root_id
    value: YOUR ROOT ID HERE

stages:
  - stage: validate
    pool:
      vmImage: "ubuntu-latest"
    jobs:
      - job: validate
        steps:
          - template: validate.yml

  - stage: deploy
    dependsOn: validate
    pool:
      vmImage: "ubuntu-latest"
    jobs:
      - job: init_and_plan
        displayName: "Initialize and Plan Dev"
        steps:
          - template: building_blocks/init.yml
            parameters:
              serviceConnectionName: ${{ variables.serviceConnectionName }}
              terraformBackendStorageAccountName: ${{ variables.terraformBackendStorageAccountName }}
              terraformBackendStorageContainerName: ${{ variables.terraformBackendStorageContainerName }}
              terraformBackendResourceGroupName: ${{ variables.terraformBackendResourceGroupName }}
              root_id: ${{ variables.root_id}}
          - template: building_blocks/plan.yml
            parameters:
              serviceConnectionName: ${{ variables.serviceConnectionName }}
              type: landingzone
      - deployment: Dev
        condition: succeeded('init_and_plan')
        displayName: Dev Deployment
        environment: dev
        workspace:
          clean: all
        strategy:
          runOnce:
            deploy:
              steps:
                - template: building_blocks/init.yml
                  parameters:
                    serviceConnectionName: ${{ variables.serviceConnectionName }}
                    terraformBackendStorageAccountName: ${{ variables.terraformBackendStorageAccountName }}
                    terraformBackendStorageContainerName: ${{ variables.terraformBackendStorageContainerName }}
                    terraformBackendResourceGroupName: ${{ variables.terraformBackendResourceGroupName }}
                    root_id: ${{ variables.root_id}}
                - template: building_blocks/deploy.yml
                  parameters:
                    serviceConnectionName: ${{ variables.serviceConnectionName }}
